[tool.poetry]
name = "practice-poetry"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["rbogart1990 <robbyt543@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
